# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 08:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_val', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='dateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_val', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='GenericRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NumberField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_val', models.IntegerField(default=0)),
                ('generic_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genRisks.GenericRisk')),
            ],
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_val', models.CharField(default='', max_length=200)),
                ('generic_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genRisks.GenericRisk')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='genericrisk',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genRisks.Users'),
        ),
        migrations.AddField(
            model_name='datefield',
            name='generic_risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genRisks.GenericRisk'),
        ),
        migrations.AddField(
            model_name='currencyfield',
            name='generic_risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genRisks.GenericRisk'),
        ),
    ]
