# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-04 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GenericRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(max_length=200)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genRisks.CustomerName')),
            ],
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field_name', models.CharField(max_length=200)),
                ('generic_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genRisks.GenericRisk')),
            ],
        ),
    ]
