# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-06 08:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genRisks', '0003_auto_20180206_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyfield',
            name='currency_field_val',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datefield',
            name='date_field_val',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='numberfield',
            name='number_field_val',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textfield',
            name='text_field_val',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='currencyfield',
            name='currency_field_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datefield',
            name='date_field_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='numberfield',
            name='number_field_name',
            field=models.CharField(max_length=200),
        ),
    ]
