# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-12 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genRisks', '0004_auto_20180206_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyfield',
            old_name='currency_field_name',
            new_name='field_name',
        ),
        migrations.RenameField(
            model_name='currencyfield',
            old_name='currency_field_val',
            new_name='field_val',
        ),
        migrations.RenameField(
            model_name='datefield',
            old_name='date_field_name',
            new_name='field_name',
        ),
        migrations.RenameField(
            model_name='datefield',
            old_name='date_field_val',
            new_name='field_val',
        ),
        migrations.RenameField(
            model_name='numberfield',
            old_name='number_field_name',
            new_name='field_name',
        ),
        migrations.RenameField(
            model_name='numberfield',
            old_name='number_field_val',
            new_name='field_val',
        ),
        migrations.RenameField(
            model_name='textfield',
            old_name='text_field_name',
            new_name='field_name',
        ),
        migrations.RenameField(
            model_name='textfield',
            old_name='text_field_val',
            new_name='field_val',
        ),
    ]
